# permissions for end users to view psqlinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: psqlinstance-viewer-role
rules:
- apiGroups:
  - dustbit.com
  resources:
  - psqlinstances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dustbit.com
  resources:
  - psqlinstances/status
  verbs:
  - get
