# permissions for end users to edit psqlinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: psqlinstance-editor-role
rules:
- apiGroups:
  - dustbit.com
  resources:
  - psqlinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dustbit.com
  resources:
  - psqlinstances/status
  verbs:
  - get
