---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - dustbit.com
  resources:
  - psqlinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dustbit.com
  resources:
  - psqlinstances/finalizers
  verbs:
  - update
- apiGroups:
  - dustbit.com
  resources:
  - psqlinstances/status
  verbs:
  - get
  - patch
  - update
